---
version: '3.8'

networks:
  oidc:
    external: true
  https_portal:
    external: true

services:
  authelia:
    image: authelia/authelia:4.38@sha256:19375b10024caeef4e0b119a6247beae84cbaa02c846cfd750e92dea910d4b6a
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./secrets
        target: /secrets
    networks:
      - oidc
      - https_portal
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      TZ: 'Europe/Paris'
      AUTHELIA_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'