---
version: '3.8'

networks:
  oidc:
    external: true
  https_portal:
    external: true
  postgres:
    external: true

services:
  authelia:
    image: authelia/authelia:4.38@sha256:19375b10024caeef4e0b119a6247beae84cbaa02c846cfd750e92dea910d4b6a
    container_name: authelia
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./secrets
        target: /secrets
    networks:
      - oidc
      - https_portal
      - postgres
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      TZ: 'Europe/Paris'
      AUTHELIA_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_KEY'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/secrets/HMAC_SECRET'
      X_AUTHELIA_CONFIG_FILTERS: 'template'