serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://oidc.issuer.powerpixel.fr
  consent: http://oidc.powerpixel.fr/consent
  login: http://oidc.powerpixel.fr/login
  logout: http://oidc.powerpixel.fr/logout
  registration: http://oidc.powerpixel.fr/register

secrets:
  system:
    - b25a58dbe61d3ceb73dd69f9da1a43db52efa5a961603fc5270ddcbd6bd0a3f4ddd69bed35e367e07b0750fb5b538531e5ed9268aac47293f7543c2850b6b33a

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: 6f9e2ae6eb63c3fc359c37b69fa8753cbe5186acf807284c532831c9be2b6d372ed7453df1d6ef7c145a2d45e7ed5d95c3dce3ad4e808ce8ad4fec876728e2ff