version: "3.9"

services:
  outline:
    user: "${UID}:${GID}"
    image: docker.getoutline.com/outlinewiki/outline:0.75.2@sha256:830923e3e7b4b3f2969db56a6033a03947f9a191d35b60a1fd80ed130ade5a1d
    env_file: ./outline.env
    networks:
      - db
      - app
    ports:
      - "3000:3000"
    volumes:
      - /data/outline/raw:/var/lib/outline/data
    depends_on:
      - app
      - postgres
      - redis
      - oidc

  redis:
    user: "${UID}:${GID}"
    image: ghcr.io/microsoft/garnet:sha-716cfb8@sha256:0e845a1647b3915dada2b3b1c1b4b1a36d586fe173e90efbbd4558363c12d86b
    env_file: ./outline.env
    networks:
      - redis
    ports:
      - "6379:6379"

networks:
  app:
  redis:
  postgres:
    external: true
  oidc:
    external: true