server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  issuer: 'authelia.com'

identity_validation:

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    # Rules applied to everyone
    - domain: 'public.example.com'
      policy: 'bypass'
    - domain: 'traefik.example.com'
      policy: 'one_factor'
    - domain: 'secure.example.com'
      policy: 'two_factor'

session:
  cookies:
    - name: 'authelia_session'
      domain: 'powerpixel.fr'  # Should match whatever your root protected domain is
      authelia_url: 'https://authelia.poerpixel.fr'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: 'redis'
    port: 6379

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'


storage:
  postgres:
    address: 'tcp://postgres:5432'
  database: 'authelia'
  schema: 'public'
  username: 'authelia'
  password: 'authelia'
  timeout: '5s'