server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  disable: false

authentication_backend:
  file:
    path: '/config/users.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain_regex: '.*\.powerpixel\.fr'
      policy: 'one_factor'

session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - name: 'authelia_session'
      domain: 'powerpixel.fr'
      authelia_url: 'https://authelia.powerpixel.fr'
      expiration: '1 hour'
      inactivity: '5 minutes'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'


storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    password: 'authelia'
    timeout: '5s'

identity_providers:
  oidc:
    jwks:
      - key: {{ secret "/secrets/JWK_OIDC_KEY" | mindent 10 "|" | msquote }}
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    clients:
      - client_id: outline
        client_name: 'Outline'
        description: Outline
        client_secret: this_is_a_secret
        public: false
        authorization_policy: one_factor
        scopes:
          - 'openid'
          - 'offline_access'
          - 'profile'
          - 'email'
        redirect_uris:
          - https://docs.powerpixel.fr/auth/oidc.callback
        userinfo_signing_algorithm: none
        token_endpoint_auth_method: 'client_secret_post'


notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'