server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  disable: false

authentication_backend:
  file:
    path: '/config/users.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain_regex: '.*\.powerpixel\.fr'
      policy: 'one_factor'

session:
  cookies:
    - name: 'authelia_session'
      domain: 'powerpixel.fr'
      authelia_url: 'https://authelia.powerpixel.fr'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: 'redis'
    port: 6379

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'


storage:
  postgres:
    address: 'tcp://postgres:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    password: 'authelia'
    timeout: '5s'

identity_providers:
  oidc:
    hmac_secret: this_is_a_secret_abc123abc123abc
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    clients:
      - id: outline
        description: Outline
        secret: this_is_a_secret
        public: false
        authorization_policy: one_factor
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://docs.powerpixel.fr/auth/oidc.callback
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'