---
# No, I will not setup an LDAP server
users:
  authelia:
    disabled: false
    displayname: "PowerPixel"
    password: "$argon2id$v=19$m=65536,t=3,p=4$7/z8r0KA9WUJrurDHSyZmA$n8cxLZJ5TsUIujTu30tzESHw4In7WLjXuMQaunf392E"
    email: powerpixel3@proton.me
    groups:
      - admins
      - docs